#!/usr/bin/bash

SCRIPT_DIR=$(dirname $0)

usage () {
    echo "Usage: $0 <mode> <toplevel module> <arguments to vsim...>"
    echo "-- <mode> must be 'batch' or 'interactive'"
}

if [ $# -lt 2 ]; then
    usage
    exit 1
fi

mode="$1"
toplevel="$2"
shift 2

case "$mode" in
    batch)
        transcript_file="$1"
        shift
        vsim -batch -nostdout -keepstdout -l "$transcript_file" -do "run -all" -onfinish exit $@ "$toplevel"
    ;;
    interactive)
        vsim $@ "$toplevel"
    ;;
    *)
        usage
        exit 1
esac
